INSERT INTO CUSTOMER(ID, NAME, SURNAME, CREATION_TIME, MODIFICATION_TIME) VALUES (1,'Toufic', 'TALIB', now(), now());
INSERT INTO CUSTOMER(ID, NAME, SURNAME, CREATION_TIME, MODIFICATION_TIME) VALUES (2,'Ramy', 'DIB', now(), now());
INSERT INTO CUSTOMER(ID, NAME, SURNAME, CREATION_TIME, MODIFICATION_TIME) VALUES (3,'Ralph', 'FLEX', now(), now());

INSERT INTO ACCOUNT(ID, DESCRIPTION, BALANCE, CUSTOMER_ID, CREATION_TIME, MODIFICATION_TIME) VALUES (1,'Account 1', 1000,1, now(), now());
